version: "3"
services:
  fronend:
    image: blinkz333/frontend:0.1
    ports:
      - 9999:80

  backend:
    image: blinkz333/backend:0.1

  mongo:
    image: blinkz333/mongo:0.1
    environment:
      MONGO_INITDB_DATABASE: mongo-test
